import Head from "next/head";
import Image from "next/image";
import { BsStars } from "react-icons/bs";
import styles from "../styles/Home.module.css";
import {
  Button,
  useColorMode,
  Text,
  Box,
  Header,
  Flex,
  Heading,
  Stack,
  VStack,
} from "@chakra-ui/react";
import { HiMoon, HiSun } from "react-icons/hi";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <motion.div
      exit={{ opacity: 1 }}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.2 }}
      className={styles.container}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box display="flex" flexDirection="column" className={styles.main}>
        <Heading as="h1" size="4xl" className={styles.title}>
          Welcome to{" "}
          <a href="https://nextjs.org">
            <Link href="/allproducts" passHref={true}>
              <Text color={colorMode === "dark" ? "green.600" : "blue.400"}>
                Dope Kicks
              </Text>
            </Link>
          </a>
        </Heading>

        <div className={styles.grid}>
          <a className={styles.card}>
            <Link href="/newproducts" passHref={true}>
              <div>
                <BsStars />
                <h2>Newest styles</h2>
                <p>Find the latest kicks here and the latest trends as well</p>
              </div>
            </Link>
          </a>

          <a className={styles.card}>
            <Link href="/allproducts" passHref={true}>
              <div>
                <BsStars />
                <h2>All Products</h2>

                <p>
                  See our whole collection of products here, including all the
                  latest styles
                </p>
              </div>
            </Link>
          </a>
        </div>
      </Box>
    </motion.div>
  );
}
